---
title: "WRK Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: cosmo
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(here)
library(shiny)
library(plotly)

source(here("utils/utils.R"))
source(here("utils/plot_education.R"))


## Load HUD Data 
# Data dictionary: https://www.huduser.gov/portal/datasets/pictures/dictionary_2021.pdf
# Number_reported is the same as the 
# hud_tracts_ak_mn_URL <- "https://www.huduser.gov/portal/datasets/pictures/files/TRACT_AK_MN_2019.xlsx"
hud_de <- read_rds(here("data/processed/hud_DE_combined.rds"))
# Estimate the number of occupied units
hud_de <- hud_de %>%
  mutate(occupied_units = case_when(pct_occupied == -4 ~ NA_real_,
                   TRUE ~ round(total_units * (pct_occupied/100), 0)))

# Target Census Tracts
target_tracts <- c("CT 30.02 (Riverside)" = "10003003002",
                   "CT 6.01" = "10003000601",
                   "CT 6.02" = "10003000602")

# Recode the missing values 
hud_de <- hud_de %>%
  mutate(across(where(is.numeric),
                ~na_if(., y = -1))) %>%
    mutate(across(where(is.numeric),
                ~na_if(., y = -4)))

# Load variable names
hud_vars_df <- read_excel(here("data/raw/hud_vars.xlsx"))
hud_vars <- hud_vars_df$variable
names(hud_vars) <- hud_vars_df$label

# Create a list of variable descriptions
hud_var_def <- hud_vars_df %>%
  select(variable, definition) %>%
  deframe()
```

# Housing {.tabsets}

Inputs {.sidebar}
-----------------------------------------------------------------------
### Outcome
```{r}

selectInput("selectedOutcome", label = NULL, 
            choices = hud_vars)
renderText({
    hud_var_def[[input$selectedOutcome]]
  })
```



```{r}
selectInput("summaryMethod", label = h3("Summary Method"),
            choices = c("Sum" = "sum", "Average" = "mean"))
```

#### Potentially-Relevant Outcomes

- % Occupied
- % Moved past year
- Average months since move-in


Row 1
-----------------------------------------------------------------------

### Delaware
```{r}
renderPlot({
  
  selectedOutcome <- sym(input$selectedOutcome)

  hud_de %>%
    plot_bar(outcome = input$selectedOutcome,
             method = input$summaryMethod,
             y_lab = names(which(hud_vars == input$selectedOutcome)))
  
})
```


### 3 Tracts Combined

```{r}
renderPlot({
  
  selectedOutcome <- sym(input$selectedOutcome)

  hud_de %>%
    filter(code %in% target_tracts) %>%
    plot_bar(outcome = input$selectedOutcome,
             method = input$summaryMethod,
             y_lab = names(which(hud_vars == input$selectedOutcome)))
  
})
```


Row 2
-----------------------------------------------------------------------


### [CT30.02 (Riverside)][CT3002]

```{r}
renderPlot({
  
  selectedOutcome <- sym(input$selectedOutcome)

  hud_de %>%
    filter(code == "10003003002") %>%
    ggplot(aes(x = year, y = !!selectedOutcome)) +
    geom_plot_col +
    ylab(names(which(hud_vars == input$selectedOutcome)))
  
})
```


### [CT 6.01 (Eastlake/Eastlawn)][CT601]

```{r}
renderPlot({
  
  selectedOutcome <- sym(input$selectedOutcome)

  hud_de %>%
    filter(code == "10003000601") %>%
    ggplot(aes(x = year, y = !!selectedOutcome)) +
    geom_plot_col +
    ylab(names(which(hud_vars == input$selectedOutcome)))
  
})
```


### [CT 6.02 (Northeast)][CT602]

```{r}
renderPlot({
  
  selectedOutcome <- sym(input$selectedOutcome)

  hud_de %>%
    filter(code == "10003000602") %>%
    ggplot(aes(x = year, y = !!selectedOutcome)) +
   geom_plot_col +
    ylab(names(which(hud_vars == input$selectedOutcome)))

  
})
```

# Education

Inputs {.sidebar}
-----------------------------------------------------------------------

### Education
```{r}
# Input
default_contentareas <- c("ELA", "MATH")
selectInput(
  inputId = "contentareas",
  label = "Content Areas", 
  choices = contentareas,
  multiple = TRUE,
  selected = default_contentareas
)

default_groups <- c("State of Delaware", "East Side Charter School")
selectInput(
  inputId = "groups",
  label = "Groups", 
  choices = rev(groups),
  multiple = TRUE,
  selected = default_groups
)

actionButton("educationReset",
             icon = icon("refresh"),
             label = "Reset")

observeEvent(input$educationReset, {
  updateSelectInput(session, "groups", selected = default_groups)
  return (NULL)
})
```


Proficiency
-----------------------------------------------------------------------
```{r}
output$plot <- renderPlotly({
  plot_education(input$contentareas, input$groups) %>%
    ggplotly(tooltip = c("y", "x", "colour"), dynamicTicks = FALSE)
})

plotlyOutput("plot", height = "100%")
```


# Workforce Development

Sidebar {.sidebar}
-----------------------------------------------------------------------
### Workforce Development
```{r}
# Load Data
graduation <- read_rds(here("data/processed/workforce_graduation.rds"))
graduation_gaps <- read_rds(here("data/processed/workforce_graduation_gaps.rds"))

```


#### Data Sources
- [Delaware Open Data - Student Graduation](https://data.delaware.gov/Education/Student-Graduation/t7e6-zcnn)

Story
-----------------------------------------------------------------------
```{r}
# Assume linear trend and calculate an average change
graduation_gaps_lm <- lm(data = graduation_gaps,
   formula  = gap ~ schoolyear)

gap_yearly_change <- graduation_gaps_lm$coefficients["schoolyear"] %>%
  sprintf("%.2f%%", .)
start_year <- graduation_gaps_lm$model$schoolyear %>% min()
end_year <-  graduation_gaps_lm$model$schoolyear %>% max()

# From 2016 and onwards
graduation_gaps_lm_2016 <- graduation_gaps %>% 
  filter(schoolyear >= 2016) %>%
  lm(data = .,
   formula  = gap ~ schoolyear)
gap_yearly_change_2016 <- graduation_gaps_lm_2016$coefficients["schoolyear"] %>%
  sprintf("%.2f%%", .)

```


### Summary

- On average, the gaps in the graduation rate with the 
state average worsened by `r gap_yearly_change` per year from `r start_year` to `r end_year`.  

- However, if we focus on 2016 onwards, the gap may be improving. On average, the gap
improved by `r gap_yearly_change_2016` per year from 2016 to 2020.


### 
```{r}
renderPlot({
  # Plot the gap with the state average
  graduation_gaps %>%
    mutate(after_2016 = schoolyear >= 2016) %>%
    ggplot(aes(x = schoolyear, y = gap, color = plot_color)) +
    geom_smooth(method = "lm", se = FALSE,
                alpha = 0.8, color = "gray") +
    geom_smooth(data = subset(graduation_gaps, schoolyear >= 2016),
                method = "lm", se = FALSE,
                color = "seagreen2") + 
    geom_segment(aes(x = schoolyear, xend = schoolyear, y = 0, yend = gap),
                 size = 1.2) + 
    geom_point(size = 5) +
    geom_hline(yintercept = 0) +
    labs(y = "Gap to Delaware Average",
         x = NULL,
         title = "Gaps in high-school graduation rate vs. state average") +
    guides(color = "none") +
    scale_y_continuous(labels = ~paste0(., "%"), limits = c(NA, 7))
})
```


High School Graduation
-----------------------------------------------------------------------

```{r}
output$graduation <- renderPlotly({
  out_plot <- graduation %>% 
    ggplot(aes(x = schoolyear, y = pctgraduates,
               color = organization, group = organization)) +
    geom_line() +
    geom_point() +
    facet_grid(. ~ ratetype) +
    scale_y_continuous(labels = ~paste0(., "%")) +
    ylab(NULL) +
    xlab(NULL) + 
    labs(color = NULL) + 
    ggtitle("High school graduation rate")
  
    return(ggplotly(out_plot))
})

plotlyOutput("graduation")
```


<!-- Markdown Links -->

[CT3002]: https://censusreporter.org/profiles/14000US10003003002-census-tract-3002-new-castle-de/
[CT602]: https://censusreporter.org/profiles/14000US10003000602-census-tract-602-new-castle-de/
[CT601]: https://censusreporter.org/profiles/14000US10003000601-census-tract-601-new-castle-de/